### ISSUE TITLE
Character Limit (prefixes)

### ISSUE THREAD

**Issue by KhaozFrost** [EverCraft/EverInformations#1]
Is there a way to increase the character limit for tags? 16 was the limit in bukkit/spigot but I've seen with ColoredTablist (though its not as good as everinformations) where it went beyond this limit and i was able to use around 20 characters.

**Comment by lesbleu** [comment]
Thanks for the issue. This modification will be implemented at the end of the week.

Example : http://www.noelshack.com/2016-23-1465440674-2016-06-09-04-38-33.png

**Comment by rexbut** [comment]
https://github.com/EverCraft/EverInformations/commit/3fc1ed1dceae9fb608b0c548d7a1493d08de9b2d

**Comment by lesbleu** [comment]
This modification is implemented. You can download all plugins in this url [download](https://github.com/EverCraft/EverAPI/releases/download/v1.2-BETA/All-Plugins-v.1.2-BETA.zip)
